### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robot-piglet**

### CODE REVIEW

**Review by ElenVolodina — APPROVED** [review]

**Comment by robot-piglet** [comment]
Shipped!

**Review by ElenVolodina — APPROVED** [review]

**Review by ElenVolodina — APPROVED** [review]

**Comment by robot-piglet** [comment]
Shipped!

**Comment by robot-piglet** [comment]
Shipped!

**Comment by robot-piglet** [comment]
Shipped!

**Pull request closed without merging**
